### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by webnoob** [prisma-utils/prisma-utils#12] opened 2022-06-18 15:44 UTC
Fresh install (first time user).

Doesn't matter if I pass a .json file as a param or not. I get this error running `npx prismerge ./prisma/prismerge.json`.

Running `yarn prismerge ./prisma/prismerge.json` reveals this as the problem:

![image](https://user-images.githubusercontent.com/10404747/174446093-4a4d5cf3-c835-42bf-8379-badd5bfcb6c8.png)

**Comment by johannesschobel** [comment] 2022-06-18 19:49
I will take a look at it on Monday. Have an idea.. thanks for reporting

**Comment by johannesschobel** [comment] 2022-06-19 13:05
Dear @webnoob ,
i have just released a new version of `prismerge` (v1.3.2) on npm. Can you please try and give feedback?

All the best,
Johannes

**Comment by tinezmatias** [comment] 2022-06-21 23:10
I have the same problem, I just remove the `.program` from `commander_1` and it's working

**Comment by johannesschobel** [comment] 2022-06-23 16:50
Does it work with the latest version of `prismerge`?
All the best

**Comment by johannesschobel** [comment] 2022-06-23 16:51
I can take a look at this next week, as I am currently at vacation..

**Comment by npwork** [comment] 2022-06-26 10:37
Same issue :(

**Comment by johannesschobel** [comment] 2022-06-27 20:33
Oh.. and i just tried the above approach with a plain `nestjs` application via
- npm install -g @nestjs/cli
- nest new NAME
- npm i -D @prisma-utils/prismerge
- npx prismerge -g -i prismerge.json
- npx prismerge -v

works as expected

**Comment by siang13** [comment] 2022-07-12 06:39
@johannesschobel I think this issue happened for people that using `yarn` instead of `npm`

**Comment by johannesschobel** [comment] 2022-07-13 06:46
Dear @siang13 , well that is kind of strange, because it seems that `yarn` would behave different than `npm` when it comes to the dependencies required (i.e., the `commander` package).

I will try to publish a new version of `prismerge` to pin these versions and maybe add the deps directly and not as peerdeps.

All the best

**Comment by overra** [comment] 2022-07-13 09:48
Yarn doesn't automatically install peer dependencies. I manually installed `commander` to get it to work for now. 

Thanks for working on this  🙌🏻

**Comment by johannesschobel** [comment] 2022-07-13 18:11
Dear @overra , @webnoob , @tinezmatias and @npwork .. can you please try with the latest version ( `v 1.6.1`) and give feedback? The `dependencies` are now described as `dependencies` and not as `peerDependencies` as before. This should - hopefully - fix the issue for you as `yarn` users ...

**Comment by overra** [comment] 2022-07-13 23:18
Hey @johannesschobel, I can confirm that it works for me now. I removed `commander`, verified that it no longer worked, then updated prismerge, and it works. 🙇🏻 Thanks!

**Comment by johannesschobel** [comment] 2022-07-14 05:34
Thank @overra for providing a feedback. I will happily close this issue then.

If something is wrong, feel free to reopen or create a new one.

Thanks for helping

**Closed** 2022-07-14 05:34 UTC
Labels: question, lib:prismerge, needs investigation
